"use strict";
const $=id=>document.getElementById(id);
const get=(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k)??JSON.stringify(d))}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const KEYS={profile:"poolProfile43",measurements:"poolMeasurements43",logs:"poolLogs43",stock:"poolStock43",tasks:"poolTasks43",dark:"poolDark43"};
const products=[
{name:"Planet Pool Multitab 200 g",kind:"maintenance",note:"Dolgotrajna večnamenska 200 g tableta. Odmerek vedno določi po embalaži glede na volumen in pretok."},
{name:"Planet Pool Chlorine Granules",kind:"chlorine",unit:"g",factor:20,perM3:10,delta:1},
{name:"Planet Pool Quick Chlor Tabs",kind:"chlorine",unit:"g",factor:20,perM3:10,delta:1},
{name:"Planet Pool pH Minus",kind:"phMinus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Planet Pool pH Plus",kind:"phPlus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Planet Pool Algaecide",kind:"algaecide",unit:"ml",factor:50,perM3:10,delta:1},
{name:"Planet Pool Flockfix",kind:"flocculant",unit:"ml",factor:100,perM3:10,delta:1},
{name:"Planet Pool Active Oxygen",kind:"oxygen",unit:"g",factor:100,perM3:10,delta:1},
{name:"Steinbach pH Minus",kind:"phMinus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Steinbach pH Plus",kind:"phPlus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Steinbach Chlorine Granules",kind:"chlorine",unit:"g",factor:15,perM3:10,delta:1},
{name:"Bayrol pH-Minus",kind:"phMinus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Bayrol pH-Plus",kind:"phPlus",unit:"g",factor:100,perM3:10,delta:.1},
{name:"Bayrol Chlorifix",kind:"chlorine",unit:"g",factor:20,perM3:10,delta:1}
];
const defaultTasks=[{id:"test",title:"Preveri pH in klor",days:3,next:null},{id:"filter",title:"Očisti ali izperi filter",days:7,next:null},{id:"robot",title:"Zaženi robotski sesalnik",days:3,next:null},{id:"water",title:"Preveri nivo vode",days:2,next:null},{id:"walls",title:"Očisti vodno linijo in stene",days:14,next:null}];
function profile(){return get(KEYS.profile,{name:"Domači bazen",l:"",w:"",d:"",v:""})}
function measurements(){return get(KEYS.measurements,[])}
function tasks(){return get(KEYS.tasks,defaultTasks.map(x=>({...x})))}
function volume(){const p=profile();return Number(p.v)||Number(p.l)*Number(p.w)*Number(p.d)||0}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function fmtDate(s){return s?new Date(s+"T12:00:00").toLocaleDateString("sl-SI"):"–"}
function download(data,name,type){const b=new Blob([data],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function selectTab(id){document.querySelectorAll(".menu-grid button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));document.querySelectorAll("section").forEach(s=>s.classList.toggle("active",s.id===id));if(id==="charts")drawMeasurementChart();if(id==="data")renderHistory();if(id==="logs")renderLogs();if(id==="stock")renderStock();location.hash=id}
document.querySelectorAll(".menu-grid button").forEach(b=>b.addEventListener("click",()=>selectTab(b.dataset.tab)));
function loadProfile(){const p=profile();$("sName").value=p.name;$("sL").value=p.l;$("sW").value=p.w;$("sD").value=p.d;$("sV").value=p.v}
function saveProfile(){set(KEYS.profile,{name:$("sName").value||"Domači bazen",l:$("sL").value,w:$("sW").value,d:$("sD").value,v:$("sV").value});$("sMsg").innerHTML='<div class="status ok">Profil je shranjen.</div>';refresh()}
function saveMeasurement(){const ph=Number($("mPh").value),cl=Number($("mCl").value);if(!ph||$("mCl").value===""){$("mMsg").innerHTML='<div class="status bad">Vnesi pH in prosti klor.</div>';return}const a=measurements();a.unshift({id:Date.now(),date:new Date().toISOString(),ph,cl,temp:$("mTemp").value,ta:$("mTa").value,cya:$("mCya").value,ch:$("mCh").value,note:$("mNote").value});set(KEYS.measurements,a);$("mMsg").innerHTML='<div class="status ok">Meritev je shranjena.</div>';refresh()}
function analysis(m){if(!m)return["warn","Ni meritev.",[]];const text=[],plan=[];if(m.ph<7){text.push("pH je prenizek.");plan.push("Najprej postopoma dodaj pH plus.")}else if(m.ph>7.4){text.push("pH je previsok.");plan.push("Najprej postopoma dodaj pH minus.")}else text.push("pH je v ciljnem območju.");if(m.cl<.5){text.push("Klor je prenizek.");plan.push("Po uravnanju pH dodaj klor.")}else if(m.cl>1.5){text.push("Klor je visok.");plan.push("Ne dodajaj klora.")}else text.push("Klor je v običajnem območju.");return[(m.ph>=7&&m.ph<=7.4&&m.cl>=.5&&m.cl<=1.5)?"ok":"warn",text.join(" "),plan]}
function refresh(){const p=profile(),m=measurements()[0],a=analysis(m);$("dName").textContent=p.name;$("dVol").textContent=volume()?volume().toFixed(1)+" m³":"–";$("dPh").textContent=m?.ph??"–";$("dCl").textContent=m?m.cl+" mg/l":"–";$("advice").className="status "+a[0];$("advice").textContent=a[1];$("todayPlan").innerHTML=a[2].length?"<ul>"+a[2].map(x=>"<li>"+x+"</li>").join("")+"</ul>":"";renderHomeTasks()}
function calcChemical(){const p=products[$("product").selectedIndex],v=volume();if(!v){$("chemResult").innerHTML='<div class="status bad">Najprej nastavi prostornino bazena.</div>';return}if(p.kind==="maintenance"){$("chemResult").innerHTML=`<div class="status warn"><b>${p.name}</b><br>${p.note}</div>`;return}const cur=Number($("currentValue").value),tar=Number($("targetValue").value);const amount=["algaecide","flocculant","oxygen"].includes(p.kind)?p.factor*(v/p.perM3):Math.abs(tar-cur)/p.delta*p.factor*(v/p.perM3);$("chemResult").innerHTML=`<div class="status ok">Orientacijski odmerek: <b>${amount.toFixed(0)} ${p.unit}</b> za ${v.toFixed(1)} m³. Preveri navodila na embalaži.</div>`}
function addLog(){const a=get(KEYS.logs,[]);a.unshift({id:Date.now(),date:new Date().toISOString(),type:$("logType").value,amount:$("logAmount").value,cost:Number($("logCost").value||0),note:$("logNote").value});set(KEYS.logs,a);renderLogs()}
function renderLogs(){const a=get(KEYS.logs,[]);$("logList").innerHTML=a.length?a.map(x=>`<div class="log"><b>${x.type}</b><div class="small">${new Date(x.date).toLocaleString("sl-SI")} · ${x.amount||"brez količine"} · ${x.cost.toFixed(2)} €</div><div>${x.note||""}</div></div>`).join(""):'<div class="small">Ni vnosov.</div>'}
function addStock(){const a=get(KEYS.stock,[]);a.push({id:Date.now(),name:$("stockName").value||"Izdelek",qty:Number($("stockQty").value||0),unit:$("stockUnit").value,min:Number($("stockMin").value||0)});set(KEYS.stock,a);renderStock()}
function renderStock(){const a=get(KEYS.stock,[]);$("stockList").innerHTML=a.length?a.map(x=>`<div class="stock"><b>${x.name}</b><div class="status ${x.qty<=x.min?"bad":"ok"}">${x.qty} ${x.unit}${x.qty<=x.min?" · nizka zaloga":""}</div><div class="actions"><button class="secondary" data-stock-dec="${x.id}">−1</button><button data-stock-inc="${x.id}">+1</button><button class="danger" data-stock-del="${x.id}">Izbriši</button></div></div>`).join(""):'<div class="small">Ni izdelkov.</div>';document.querySelectorAll("[data-stock-dec]").forEach(b=>b.onclick=()=>changeStock(Number(b.dataset.stockDec),-1));document.querySelectorAll("[data-stock-inc]").forEach(b=>b.onclick=()=>changeStock(Number(b.dataset.stockInc),1));document.querySelectorAll("[data-stock-del]").forEach(b=>b.onclick=()=>deleteStock(Number(b.dataset.stockDel)))}
function changeStock(id,d){const a=get(KEYS.stock,[]),x=a.find(v=>v.id===id);if(x)x.qty=Math.max(0,x.qty+d);set(KEYS.stock,a);renderStock()}
function deleteStock(id){set(KEYS.stock,get(KEYS.stock,[]).filter(x=>x.id!==id));renderStock()}
function clearStock(){if(confirm("Res želiš izbrisati vso zalogo?")){set(KEYS.stock,[]);renderStock()}}
function taskState(t){if(!t.next)return["warn","Datum ni določen"];const a=new Date();a.setHours(0,0,0,0);const b=new Date(t.next+"T12:00:00");b.setHours(0,0,0,0);const n=Math.round((b-a)/86400000);return n<0?["bad",`Zamuja ${-n} dni`]:n===0?["bad","Danes"]:n===1?["warn","Jutri"]:["ok",`Čez ${n} dni`]}
function renderTasks(){const a=tasks();$("taskList").innerHTML=a.map((t,i)=>{const s=taskState(t);return`<div class="task"><b>${t.title}</b><div class="grid"><div><label>Ponovi vsakih X dni</label><input data-task-days="${i}" type="number" min="1" value="${t.days}"></div><div><label>Prvi datum</label><input data-task-date="${i}" type="date" value="${t.next||""}"></div></div><div class="status ${s[0]}">${s[1]}${t.next?" · "+fmtDate(t.next):""}</div><div class="actions"><button data-task-done="${i}">Opravljeno danes</button><button class="secondary" data-task-cal="${i}">Dodaj ponavljajoči opomnik</button></div></div>`}).join("");document.querySelectorAll("[data-task-days]").forEach(el=>el.onchange=()=>{const x=tasks(),i=Number(el.dataset.taskDays);x[i].days=Math.max(1,Number(el.value)||1);set(KEYS.tasks,x);renderTasks()});document.querySelectorAll("[data-task-date]").forEach(el=>el.onchange=()=>{const x=tasks(),i=Number(el.dataset.taskDate);x[i].next=el.value||null;set(KEYS.tasks,x);renderTasks();renderHomeTasks()});document.querySelectorAll("[data-task-done]").forEach(el=>el.onclick=()=>doneTask(Number(el.dataset.taskDone)));document.querySelectorAll("[data-task-cal]").forEach(el=>el.onclick=()=>calendarTask(Number(el.dataset.taskCal)))}
function renderHomeTasks(){$("homeTasks").innerHTML=tasks().slice(0,4).map(t=>{const s=taskState(t);return`<span class="pill">${t.title}: ${s[1]}</span>`}).join("")}
function doneTask(i){const a=tasks(),d=new Date();d.setDate(d.getDate()+Number(a[i].days));a[i].next=isoDate(d);set(KEYS.tasks,a);renderTasks();renderHomeTasks()}
function calendarTask(i){const t=tasks()[i];if(!t.next){alert("Najprej določi prvi datum.");return}const start=t.next.replaceAll("-","")+"T090000",end=t.next.replaceAll("-","")+"T091500";const ics=["BEGIN:VCALENDAR","VERSION:2.0","CALSCALE:GREGORIAN","PRODID:-//Moj bazen//SL","BEGIN:VEVENT",`UID:pool-${t.id}-${Date.now()}@moj-bazen`,`DTSTART:${start}`,`DTEND:${end}`,`RRULE:FREQ=DAILY;INTERVAL=${Math.max(1,Number(t.days))}`,`SUMMARY:Moj bazen: ${t.title}`,"BEGIN:VALARM","TRIGGER:PT0M","ACTION:DISPLAY",`DESCRIPTION:${t.title}`,"END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n");download(ics,`bazen-${t.id}-vsakih-${t.days}-dni.ics`,"text/calendar;charset=utf-8")}
async function requestNotifications(){if(!("Notification" in window)){alert("Za zanesljiva opozorila uporabi koledarski opomnik.");return}const r=await Notification.requestPermission();alert(r==="granted"?"Obvestila so dovoljena.":"Obvestila niso dovoljena.")}
function drawLineChart(canvas,data,series){const ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height,pad={l:48,r:24,t:22,b:38};ctx.clearRect(0,0,W,H);ctx.strokeStyle="#d8e7ef";ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad.t+i*(H-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke()}if(data.length<2){ctx.fillStyle="#687f90";ctx.fillText("Za graf sta potrebni vsaj dve meritvi.",pad.l+10,H/2);return}series.forEach((s,si)=>{ctx.strokeStyle=si===0?"#0878b8":"#e68a00";ctx.lineWidth=3;ctx.beginPath();data.forEach((row,i)=>{const x=pad.l+i*(W-pad.l-pad.r)/(data.length-1),y=H-pad.b-(Number(row[s.key])-s.min)/(s.max-s.min)*(H-pad.t-pad.b);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()});ctx.fillStyle="#687f90";ctx.font="12px sans-serif";data.forEach((row,i)=>{if(i%Math.ceil(data.length/6)===0){const x=pad.l+i*(W-pad.l-pad.r)/(data.length-1);ctx.fillText(row.label,x-15,H-12)}})}
function drawMeasurementChart(){const key=$("chartMetric").value,ranges={ph:[6.5,8],cl:[0,3],temp:[5,40],ta:[0,200],cya:[0,120],ch:[0,500]},range=ranges[key],data=measurements().slice(0,30).reverse().map(m=>({...m,label:new Date(m.date).toLocaleDateString("sl-SI",{day:"2-digit",month:"2-digit"})}));drawLineChart($("mainChart"),data,[{key,min:range[0],max:range[1]}])}
async function loadWeather(){const summary=$("weatherSummary");summary.innerHTML='<div class="status warn">Pridobivam napoved …</div>';if(!navigator.geolocation){summary.innerHTML='<div class="status bad">Lokacija ni podprta.</div>';return}navigator.geolocation.getCurrentPosition(async pos=>{try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&forecast_days=7&timezone=auto`;const r=await fetch(url),j=await r.json();const data=j.daily.time.map((date,i)=>({label:new Date(date+"T12:00:00").toLocaleDateString("sl-SI",{weekday:"short"}),max:j.daily.temperature_2m_max[i],min:j.daily.temperature_2m_min[i],rain:j.daily.precipitation_sum[i]}));set("poolWeather43",data);renderWeather(data)}catch{summary.innerHTML='<div class="status bad">Napovedi ni mogoče pridobiti.</div>'}},()=>summary.innerHTML='<div class="status bad">Dostop do lokacije ni dovoljen.</div>')}
function renderWeather(data=get("poolWeather43",[])){if(!data.length)return;const hot=data.some(x=>x.max>=28),wet=data.some(x=>x.rain>=5),tips=[];if(hot)tips.push("V vročih dneh preveri klor pogosteje.");if(wet)tips.push("Po močnejšem dežju preveri pH, klor in nivo vode.");if(!tips.length)tips.push("Napoved ne zahteva posebnih ukrepov.");$("weatherSummary").innerHTML=`<div class="status ok">${tips.join(" ")}</div>`;const c=$("weatherChart"),ctx=c.getContext("2d"),W=c.width,H=c.height,p={l:48,r:28,t:22,b:42};ctx.clearRect(0,0,W,H);ctx.strokeStyle="#d8e7ef";for(let i=0;i<5;i++){const y=p.t+i*(H-p.t-p.b)/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke()}data.forEach((x,i)=>{const px=p.l+i*(W-p.l-p.r)/(data.length-1),bh=Math.min(80,x.rain*5);ctx.fillStyle="rgba(24,166,202,.30)";ctx.fillRect(px-14,H-p.b-bh,28,bh)});[["max","#e08122"],["min","#0878b8"]].forEach(([key,color])=>{ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();data.forEach((x,i)=>{const px=p.l+i*(W-p.l-p.r)/(data.length-1),py=H-p.b-(x[key]+5)/45*(H-p.t-p.b);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)});ctx.stroke()});ctx.fillStyle="#687f90";ctx.font="12px sans-serif";data.forEach((x,i)=>{const px=p.l+i*(W-p.l-p.r)/(data.length-1);ctx.fillText(x.label,px-12,H-15)});ctx.fillText("oranžno: max °C · modro: min °C · stolpci: dež",p.l,15)}
function renderHistory(){const a=measurements();$("historyBody").innerHTML=a.length?a.map(m=>`<tr><td>${new Date(m.date).toLocaleString("sl-SI")}</td><td>${m.ph}</td><td>${m.cl}</td><td>${m.temp||"–"}</td><td><button class="danger" data-measure-del="${m.id}" style="padding:5px;margin:0">×</button></td></tr>`).join(""):'<tr><td colspan="5">Ni meritev.</td></tr>';document.querySelectorAll("[data-measure-del]").forEach(b=>b.onclick=()=>{set(KEYS.measurements,measurements().filter(x=>x.id!==Number(b.dataset.measureDel)));renderHistory();refresh()})}
function exportJSON(){download(JSON.stringify({version:"4.3",profile:profile(),measurements:measurements(),logs:get(KEYS.logs,[]),stock:get(KEYS.stock,[]),tasks:tasks()},null,2),"moj-bazen-v4-3-backup.json","application/json")}
function exportCSV(){const rows=[["Datum","pH","Klor","Temperatura","TA","CYA","CH"],...measurements().map(m=>[m.date,m.ph,m.cl,m.temp,m.ta,m.cya,m.ch])];download(rows.map(r=>r.join(";")).join("\n"),"moj-bazen-meritve.csv","text/csv")}
function importJSON(file){const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result);if(o.profile)set(KEYS.profile,o.profile);if(o.measurements)set(KEYS.measurements,o.measurements);if(o.logs)set(KEYS.logs,o.logs);if(o.stock)set(KEYS.stock,o.stock);if(o.tasks)set(KEYS.tasks,o.tasks);loadProfile();refresh();renderTasks();alert("Podatki so uvoženi.")}catch{alert("Datoteka ni veljavna.")}};r.readAsText(file)}
function toggleDark(){document.body.classList.toggle("dark");set(KEYS.dark,document.body.classList.contains("dark"))}
$("product").innerHTML=products.map(p=>`<option>${p.name}</option>`).join("");$("saveMeasurementBtn").onclick=saveMeasurement;$("saveProfileBtn").onclick=saveProfile;$("calcChemicalBtn").onclick=calcChemical;$("addLogBtn").onclick=addLog;$("addStockBtn").onclick=addStock;$("clearStockBtn").onclick=clearStock;$("requestNotificationsBtn").onclick=requestNotifications;$("chartMetric").onchange=drawMeasurementChart;$("loadWeatherBtn").onclick=loadWeather;$("exportJsonBtn").onclick=exportJSON;$("exportCsvBtn").onclick=exportCSV;$("printBtn").onclick=()=>window.print();$("importJsonBtn").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{if(e.target.files[0])importJSON(e.target.files[0])};$("darkModeBtn").onclick=toggleDark;
if(get(KEYS.dark,false))document.body.classList.add("dark");loadProfile();refresh();renderTasks();renderLogs();renderStock();renderHistory();renderWeather();const initial=location.hash.replace("#","");if(document.getElementById(initial))selectTab(initial);if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").then(r=>r.update()).catch(()=>{});
