(()=>{"use strict";
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const topics=[
{id:"filter",icon:"🛠️",title:"Servis filtra",desc:"Notranjost, tlak, laterale in tesnila",keywords:"filter manometer laterale centralna cev tlak puščanje servis",base:["Pripravi orodje in delovno mesto","Izklopi električno napajanje","Zapri vse potrebne ventile","Sprosti tlak na manometru","Izpusti vodo iz posode","Fotografiraj priključke","Odklopi cevi ali spojke","Odstrani 6-potni ventil","Zaščiti centralno cev","Odstrani filtrirni medij","Očisti notranjost posode","Preglej centralno cev","Preglej zbirne krake","Preveri razdelilnik vode","Preglej O-tesnila","Zamenjaj poškodovane dele","Napolni tretjino posode z vodo","Dodaj filtrirni medij","Sestavi in preveri tesnjenje","Izvedi BACKWASH in RINSE"]},
{id:"pump",icon:"⚙️",title:"Črpalka",desc:"Predfilter, rotor, tesnila in zrak v sistemu",keywords:"črpalka motor rotor košara predfilter tesnilo zrak brni pušča",base:["Izklopi napajanje črpalke","Zapri sesalni in povratni ventil","Sprosti tlak v sistemu","Odpri prozorni pokrov","Odstrani košaro predfiltra","Očisti košaro in ohišje","Preveri pokrov za razpoke","Očisti utor O-tesnila","Preglej in namaži O-tesnilo","Preveri sesalne spoje","Preveri nivo vode v bazenu","Preveri loputo skimerja","Ročno preveri prost rotor","Odstrani vidno umazanijo","Napolni ohišje z vodo","Pravilno zapri pokrov","Počasi odpri ventile","Zaženi črpalko","Odzrači sistem","Preveri zvok, pretok in puščanje"]},
{id:"valve",icon:"🔄",title:"Ventili",desc:"FILTER, BACKWASH, RINSE in drugi položaji",keywords:"ventil filter backwash rinse waste recirculate closed šestpotni",base:["Ustavi črpalko","Preveri položaj FILTER","Spoznaj smer običajnega pretoka","Preveri začetni tlak","Ustavi črpalko pred premikom","Nastavi BACKWASH","Odpri pot v odtok","Zaženi izpiranje","Opazuj kontrolno steklo","Ustavi črpalko","Nastavi RINSE","Izpiraj 20–30 sekund","Ustavi črpalko","Vrni na FILTER","Preveri položaj WASTE","Preveri položaj RECIRCULATE","Spoznaj nevarnost CLOSED","Preglej ročico in vzmet","Preveri tesnilo zvezde","Preveri puščanje v odtok"]},
{id:"afm",icon:"💎",title:"AFM",desc:"Sloji, količina in pravilno polnjenje",keywords:"afm aktivno filtrirno steklo glass media granulacija grade",base:["Preveri model in prostornino filtra","Poišči dovoljeno maso medija","Izračunaj potrebno količino AFM","Pripravi grobo spodnjo frakcijo","Pripravi fino zgornjo frakcijo","Izklopi in izprazni filter","Odstrani obstoječi medij","Očisti posodo","Preglej laterale","Zaščiti centralno cev","Dodaj vodo do tretjine","Nasuj grobo frakcijo","Poravnaj prvi sloj","Nasuj fino frakcijo","Ne presezi oznake polnitve","Odstrani zaščito cevi","Očisti tesnilne površine","Ponovno sestavi ventil","Izvedi daljši BACKWASH","Izvedi RINSE in preklopi na FILTER"]},
{id:"sand",icon:"🏖️",title:"Pesek",desc:"Granulacija, menjava in prvi zagon",keywords:"pesek kremenčev granulacija 0.4 0.8 1.2 menjava",base:["Preberi tablico filtra","Preveri priporočeno granulacijo","Pripravi pravilno količino peska","Izklopi napajanje","Zapri ventile","Izpusti filter","Odstrani ventil","Zapri centralno cev","Odstrani stari pesek","Operi prazno posodo","Preglej laterale","Zamenjaj poškodovane krake","Dodaj zaščitno vodo","Najprej dodaj grobo frakcijo","Nato dodaj fino frakcijo","Poravnaj površino","Očisti vrat posode","Namesti in zatesni ventil","Izvedi BACKWASH do čiste vode","Izvedi RINSE in zapiši začetni tlak"]},
{id:"winter",icon:"❄️",title:"Zimska priprava",desc:"Zaščita bazena in opreme pred zmrzaljo",keywords:"zima prezimovanje zmrzal izpust pokrivalo čepi",base:["Temeljito očisti bazen","Uravnovesi pH vode","Izvedi zaključno dezinfekcijo","Očisti filter z BACKWASH","Izvedi RINSE","Izklopi ogrevanje","Znižaj nivo vode po sistemu","Izprazni skimer in cevi","Namesti zimske čepe","Izprazni črpalko","Odstrani izpustne čepe","Izprazni filter","Ventil postavi v zimski položaj","Izprazni dodatno opremo","Zaščiti občutljive dele","Dodaj zimsko sredstvo po navodilih","Namesti zimske plovce","Preveri odvod padavinske vode","Namesti in napni pokrivalo","Shrani seznam odstranjenih delov"]},
{id:"spring",icon:"🌞",title:"Spomladanski zagon",desc:"Ponovni zagon po zimskem mirovanju",keywords:"pomlad zagon odprtje sezona polnjenje",base:["Odstrani vodo in umazanijo s pokrivala","Odstrani in očisti pokrivalo","Preglej bazensko folijo","Odstrani zimske plovce","Odstrani zimske čepe","Namesti izpustne čepe opreme","Sestavi črpalko","Preglej O-tesnila","Priključi cevi","Odpri ventile","Dopolni nivo vode","Napolni predfilter črpalke","Zaženi sistem in odzrači","Preveri puščanje","Izvedi BACKWASH","Izvedi RINSE","Izmeri pH in alkaliteto","Uredi pH","Izvedi začetno dezinfekcijo","Filtriraj in ponovno izmeri vodo"]},
{id:"trouble",icon:"⚠️",title:"Odpravljanje napak",desc:"Motna voda, slab pretok, hrup in puščanje",keywords:"napaka motna mlečna zelena voda slab pretok visok tlak nizek tlak hrup puščanje",base:["Določi glavni simptom","Zapiši trenutni tlak","Preveri nivo vode","Preveri položaje ventilov","Preglej košare skimerja","Preglej košaro črpalke","Preveri vidne zračne mehurčke","Poslušaj zvok črpalke","Preveri sesalne spoje","Preveri povratni pretok","Izmeri pH","Izmeri prosti klor","Preveri čas filtracije","Izvedi BACKWASH","Izvedi RINSE","Preveri medij v bazenu","Preveri puščanje v odtok","Preveri morebitno blokado rotorja","Izvedi priporočeni popravek","Po 12–24 urah ponovno oceni stanje"]}
];
const notes={filter:"Delaj previdno okoli zbirnih krakov; stara plastika je lahko krhka.",pump:"Črpalke nikoli ne zaganjaj na suho. Ob električni napaki pokliči usposobljenega serviserja.",valve:"Ročico vedno prestavljaj samo pri popolnoma ugasnjeni črpalki.",afm:"Natančno razmerje frakcij preveri v navodilih proizvajalca filtra in AFM.",sand:"Uporabi opran kremenčev filtrirni pesek, ne gradbenega peska.",winter:"Bazena s folijo praviloma ne izprazni v celoti; upoštevaj konstrukcijo in navodila proizvajalca.",spring:"Pred meritvami naj voda nekaj časa kroži, da dobiš reprezentativen vzorec.",trouble:"Če izklaplja FID, smrdi po zažganem ali voda uhaja ob električnih delih, sistem takoj izklopi."};
let active=null,idx=0; const done=JSON.parse(localStorage.getItem("interactiveManual56")||"{}");
function svg(topic,n){const hue={filter:198,pump:210,valve:174,afm:185,sand:42,winter:204,spring:92,trouble:8}[topic.id];const rot=(n*17)%360;return `<svg viewBox="0 0 640 360" role="img" aria-label="Ilustracija: ${esc(topic.base[n])}"><defs><linearGradient id="g${topic.id}${n}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${hue} 85% 92%)"/><stop offset="1" stop-color="hsl(${hue} 75% 72%)"/></linearGradient><marker id="a${topic.id}${n}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="hsl(${hue} 75% 38%)"/></marker></defs><rect width="640" height="360" rx="26" fill="url(#g${topic.id}${n})"/><circle cx="320" cy="170" r="105" fill="white" opacity=".86"/><g transform="translate(320 170) rotate(${rot})"><rect x="-62" y="-90" width="124" height="180" rx="48" fill="hsl(${hue} 70% 48%)" opacity=".9"/><rect x="-45" y="-60" width="90" height="115" rx="22" fill="white" opacity=".78"/><path d="M-145 0 H-72" stroke="hsl(${hue} 75% 38%)" stroke-width="13" marker-end="url(#a${topic.id}${n})"/><path d="M72 0 H145" stroke="hsl(${hue} 75% 38%)" stroke-width="13" marker-end="url(#a${topic.id}${n})"/></g><circle cx="94" cy="76" r="38" fill="white"/><text x="94" y="88" text-anchor="middle" font-size="34">${topic.icon}</text><text x="320" y="320" text-anchor="middle" font-family="system-ui" font-size="24" font-weight="800" fill="#123044">${n+1}. ${esc(topic.base[n])}</text></svg>`}
function renderHome(filter=""){const q=filter.trim().toLowerCase();const matches=topics.filter(t=>(t.title+" "+t.desc+" "+t.keywords+" "+t.base.join(" ")).toLowerCase().includes(q));$("imCategories").innerHTML=matches.map(t=>{const c=(done[t.id]||[]).length;return `<button class="im-category" data-id="${t.id}"><span>${t.icon}</span><b>${t.title}</b><small>${t.desc}</small><em>${c}/20 opravljenih</em></button>`}).join("");$("imSearchResults").innerHTML=q&&!matches.length?'<div class="status warn">Ni zadetkov. Poskusi z drugim izrazom.</div>':"";document.querySelectorAll(".im-category").forEach(b=>b.onclick=()=>openGuide(b.dataset.id));updateCount()}
function updateCount(){const n=Object.values(done).reduce((a,x)=>a+x.length,0);$("imProgressCount").textContent=n}
function openGuide(id,step=0){active=topics.find(t=>t.id===id);idx=step;$("imHome").hidden=true;$("imGuide").hidden=false;$("imGuideIcon").textContent=active.icon;$("imGuideTitle").textContent=active.title;renderStep()}
function renderStep(){const title=active.base[idx], completed=(done[active.id]||[]).includes(idx);$("imGuideMeta").textContent=`Korak ${idx+1} od 20 · ${Math.round((idx+1)/20*100)} %`;$("imBar").style.width=`${(idx+1)/20*100}%`;$("imStep").innerHTML=`<article class="im-step-card"><div class="im-illustration">${svg(active,idx)}</div><div class="im-step-copy"><span class="im-step-number">KORAK ${idx+1}</span><h3>${esc(title)}</h3><p>${esc(stepText(active,idx))}</p><div class="im-tip"><b>Pomembno</b><span>${esc(notes[active.id])}</span></div></div></article>`;$("imPrev").disabled=idx===0;$("imNext").disabled=idx===19;$("imComplete").textContent=completed?"Opravljeno ✓":"Označi opravljeno ✓";$("imComplete").classList.toggle("completed",completed)}
function stepText(t,n){const action=t.base[n];const endings=["Pred nadaljevanjem preveri, da je ta korak v celoti zaključen.","Delaj počasi in opazuj morebitno puščanje ali nenavaden upor.","Po izvedbi fotografiraj stanje, da ga lahko primerjaš ob naslednjem servisu.","Uporabi osebno zaščitno opremo in navodila proizvajalca svoje opreme."];return `${action}. ${endings[n%endings.length]}`}
$("imSearch").addEventListener("input",e=>renderHome(e.target.value));$("imPrev").onclick=()=>{if(idx>0){idx--;renderStep()}};$("imNext").onclick=()=>{if(idx<19){idx++;renderStep()}};$("imComplete").onclick=()=>{const arr=done[active.id]||[];const p=arr.indexOf(idx);p<0?arr.push(idx):arr.splice(p,1);done[active.id]=arr.sort((a,b)=>a-b);localStorage.setItem("interactiveManual56",JSON.stringify(done));renderStep();updateCount()};$("imClose").onclick=()=>{$("imGuide").hidden=true;$("imHome").hidden=false;renderHome($("imSearch").value)};renderHome();
})();
